name: oed
channels:
  - defaults
  - conda-forge
  - openbabel
dependencies:
  - python==3.7.*
  - numpy==1.19.*
  - pandas==1.*
  - scikit-learn==0.23.*
  - matplotlib==3.*
  - rdkit==2020.03.*
  - ase==3.21.*
  - scipy==1.5.2
  - modal==0.4.*
  - tqdm
  - jupyterlab
  - pip
